name: Run Selenium Tests with Allure

on:
  push:
    branches: [ '*' ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.14.0-beta.2

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install allure-pytest

    - name: Install Chrome
      uses: browser-actions/setup-chrome@v1
      
    - name: Install Allure via npm
      run: |
        sudo apt-get update
        curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
        sudo apt-get install -y nodejs
        sudo npm install -g allure-commandline

    - name: Run tests
      run: |
        pytest --alluredir=allure-results

    - name: Generate Allure report
      run: allure generate allure-results --clean -o site

    - name: Deploy Allure report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
