name: Run Selenium Tests with Allure

on:
  push:
    branches: [ 'pytest+allure' ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install allure-commandline

    - name: Install Chrome
      uses: browser-actions/setup-chrome@v1

    - name: Run tests
      run: |
        pytest --alluredir=allure-results

    - name: Generate Allure report
      run: allure generate allure-results --clean -o site

    - name: Deploy Allure report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
